version: '3.2'
services:
  db:
    image: postgres
    container_name: 'postgres'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=diploma
    ports:
      - '5432:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data
    command: 'postgres -c log_destination=stderr -c logging_collector=on -c log_directory=/var/log/postgresql'